### ISSUE TITLE
Coolant velocity varying in straight vertical channels

### ISSUE THREAD

**Issue by dug20** [cuspaceflight/bamboo#23]
In this example, the vertical coolant channels are straight, so their area shouldn't be changing, but it seems the static pressure calculations might be thinking the channels are following the inner contour (i.e. the inside wall of graphite in this case).

![image](https://user-images.githubusercontent.com/61093535/113216064-b45fbe80-9273-11eb-9c29-b2ad512f6596.png)
![image](https://user-images.githubusercontent.com/61093535/113216081-ba559f80-9273-11eb-8fd8-7d5a82ec3a28.png)

**Comment by hf360F** [comment]
Yeah I first noticed this before the ablative got added and was wondering how the channels would be built with varying width.
Spiral + ablative engines will also be affected, but in a less obvious way - the length returned by `channel_geometry` will be too short, because the spiral radius will be wrong.

I think the `has_ablative` flag is a good way to fix this, but it seems to me like the ablator can be added after the regen jacket, so the `CoolingJacket` object can't _necessarily_ inherit that information from the engine.

What I've done is add two checks -
One is in `add_cooling_jacket` - if an ablator has already been added, then this is passed into the `CoolingJacket` configuration.
The second is in `add_ablative` - if a `CoolingJacket` has already been added, then the `has_ablator` attribute that's been added to `CoolingJacket` is set to True. (at the moment an exception is raised if there is no cooling jacket but I put it in an if statement in case ablative only is added)

This should handle all types of engine and both ways of creating an engine with regen and an ablator.

CoolingJacket now inherits the engine geometry in order to have access to the maximum engine radius, so it can ignore the y values used for the nozzle contours.
Then, in  `CoolingJacket.A()`, if `has_ablator` (for the `CoolingJacket`) is true then the radius is always the chamber radius, the y value is disregarded.
In `Engine.channel_geometry()`, `has_ablator` (for the `Engine`) is true, then the spiral radius is similarly always the chamber radius.

New result with vertical channels in `regen_ablative_example`:
![image](https://user-images.githubusercontent.com/77733422/113224785-14f6f780-9284-11eb-8719-4242a83c13b2.png)

And for spiral channels, much more subtle:
![image](https://user-images.githubusercontent.com/77733422/113224492-7b2f4a80-9283-11eb-9a37-d3a7f25d4034.png)

**Comment by hf360F** [comment]
There was a bug in how the spiral channel length was worked out, the spiral length should be longer, not shorter, with the fix in place because the radius never decreases below `chamber_radius`, so it didn't make sense that the "fixed" pressure drop is lower. This bug is now also fixed.
